### ISSUE TITLE
Team Project Deliverable 1

### ISSUE THREAD

**Issue by Nightsquid7** [Nightsquid7/CEN-4020-Group-Project#3]
As the start of the Team project, each member of the team will submit a document, either typed into Canvas directly or through the delivery of a Ms Word (.docx) or Adobe (.pdf) document the following items.  
** figured we could write this here.
1. The Team members full name and FSUID (login ID).  There shall be no less then 3 and no more than 5 team members. 

Daniel Powley       (dcp18)
Sheikh Khaled       (slk18bg)
Steven Berkowitz  (sab10d)
Wendy Slattery     (wls12) 
Luca Labruna        (ldl17c)

2.  The name of the Team. 
Plastic Frogs, Amazing!

3.  A one or two paragraph description of the project that you propose.

**Comment by Nightsquid7** [comment]
Our group project is to create a game using the unity game engine, and c#. We are considering remaking a limited version of the game "Enter the Gungan" https://www.bing.com/search?q=enter+the+gungeon+gameplay&qs=AS&pq=enter+the+gungeon+g&sc=8-19&cvid=10FB81F0BB254E978172F2B5D9BB87A4&FORM=EX0023&sp=1&shtp=Sms&shid=d7aef0d5-b3db-4afc-8407-a9e53bc3a550&shtk=RW50ZXIgdGhlIEd1bmdlb24gLSAxLiBHcmltIEd1bmdvbmVlciAtIExldCdzIFBsYXkgRW50ZXIgLi4u&shdk=Q2hlY2sgb3V0IHRoaXMgdmlkZW8uIEF2YWlsYWJsZSB2aWEgeW91dHViZS5jb20u&shhk=Gtprqsnx4i7zU8Mnjq0d5x7mpszoDFq%2BOq02yQJHnI4%3D&shtc=0&shth=OSH.vVY%252BmHujnMpL%252BfqFKPyTnw

**Comment by Nightsquid7** [comment]
- [ ] Add Luca to github

**Comment by lucacs** [comment]
Hello

**Comment by danipo** [comment]
#3. We will be using Unity primarily in our project, and will be coding mainly in C#. Our areas of expertise will consist of:

- Character and environment art creation
- Basic game design in 2D (collisions, scoring, computer generated AI, game fundamentals)
- Android programming (though this could be scaled back to a desktop program)

Further explorations could include publishing and porting to other platforms, but that would be purely dependent on time constraints and auxiliary research.

**Comment by wslatts** [comment]
Looks good, Daniel? Do we want to add any background music or sounds as part of description (added feature)?

**Comment by danipo** [comment]
Yes, I do think the bullet points could be fleshed out more, feel free to edit

**Comment by wslatts** [comment]
Ok, I edited, but I'm also a wordy person so feel free to chop and shorten if you want and/or if you think that looks too ambitious. I actually don't really know what is or isn't ambitious, but figured it looks good to show him where our minds are going into seeing options to develop the project further.

**Comment by Nightsquid7** [comment]
Looking great to me!

**Comment by lucacs** [comment]
Oh seems Github doesn't keep spaces, think once I'm done I'm pasting everything on a word document and send you to download? Not that it really matters ahah

**Comment by Nightsquid7** [comment]
Alright yall, looks successful! gonna close this issue
