### ISSUE TITLE
Decide on game idea

### ISSUE THREAD

**Issue by Nightsquid7** [Nightsquid7/CEN-4020-Group-Project#5]
Also testing slack notifications for folks..

So, should we commit to the gungeon game idea?

If anyone else wants to submit a plan that’d be great, else looks like we’re gonna try a Gungeon clone right?

**Comment by danipo** [comment]
I'm fine with this. Are we targeting Android for this or PC?

**Comment by slk18bg** [comment]
I'm fine with Gungeon as well.

**Comment by wslatts** [comment]
Good with gungeon and open to others if need be.
