### ISSUE TITLE
Weekly report  - easy stuff 5 minutes - due sep 20 midnight

### ISSUE THREAD

**Issue by lucacs** [Nightsquid7/CEN-4020-Group-Project#7]
**1.  Team Name:**
     Plastic Frogs, Amazing!

**2. Team Members:**
    Daniel Powley
    Wendy Slattery
    Luca Labruna
    Sheikh Khaled
    Steven Berkowitz 

**3. Once Sentence Project Description**
    Game based on "Enter the Gungeon" developed with Unity and C#

**4.  Team Meetings this week?:** 
     Wednesday 18 group call (Discord) but we discuss daily on Slack also

**5. What are you working on this week?** 
       Production schedule, decide platform and language, divide roles

**6. What are you planning to work on next week?** 
      Setting up a shared working environment, research tools (platform and language), complete a basic game tutorial, planning development tasks for the game

**7. What problems have you run into?** 
      Anticipating which aspects of development may have challenges or complexities which need highest attention.

**8. Do you have a plan to resolve the problems?** 
      Collaborating on best strategies toward approach, research, division of tasks while maintaining cohesive and overlapping duties.  First goal is simplified, basic graphics, formalize functionality, and then build upward.  

**Name of Person Giving Report**
Luca Labruna

**Comment by Nightsquid7** [comment]
Looks good, thanks Luca!

Some things
6: next week: planning development tasks for the game

**Comment by lucacs** [comment]
feel free to add anything, was just a draft, he said one or two lines for field so anything its good

**Comment by wslatts** [comment]
Looks good, Luca!  Thanks for putting that together.  I added to 7 & 8 since nothing was really there yet, but you guys feel free to change it up if you want

**Comment by lucacs** [comment]
thanks a lot Wendy, yeah I was just gonna put like some commutations and organization difficulties or something XD don t think this is graded , is more so he knows we re not doing it at the last minute
